---
services:
  rancher:
    restart: unless-stopped
    container_name: rancher
    ports:
      - 8778:80
      - 8779:443
    privileged: true
    image: rancher/rancher:latest
  #  command:  --acme-domain rancher.tawfiqulbari.work
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.rancher.rule=Host(`rancher.tawfiqulbari.work`)"
  #    - "traefik.http.routers.rancher.entrypoints=https"
  #    - "traefik.http.routers.rancher.tls=true"
  #    - "traefik.http.services.rancher.loadbalancer.server.port=80"
    networks:
      - proxy
networks:
  proxy:
    external: true 
