---
services:
  database:
    image: mariadb:lts-ubi9
    container_name: wp-mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - proxy
  
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myadmin.rule=Host(`myadmin.tawfiqulbari.work`)"
      - "traefik.http.routers.myadmin.entrypoints=https"
      - "traefik.http.routers.myadmin.tls=true"
      - "traefik.http.services.myadmin.loadbalancer.server.port=80"
    
    restart: unless-stopped
    container_name: wp-phpmyadmin
    networks:
      - proxy
    
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

  wordpress:
    depends_on:
      - database
    image: wordpress:php8.3-apache
    container_name: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`blog.tawfiqulbari.work`)"
      - "traefik.http.routers.wordpress.entrypoints=https"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    restart: unless-stopped
        
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - proxy


volumes:
  db-data:
    external: true
  wordpress-data:
    external: true

networks:
  proxy:
    external: true