services:
   traefik:
     image: traefik:v3.0
     restart: always
     command:
       - "--log.level=DEBBUG"
       - "--api.insecure=true"
       - "--providers.docker=true"
       - "--providers.docker.exposedbydefault=true"
       - "--entrypoints.web.address=:80"
       - "--entrypoints.websecure.address=:443"
       - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
       - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
     ports:
       - 80:80
       - 443:443
     networks:
       - traefik
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     container_name: traefik
   pihole:
     image: pihole/pihole:2024.05.0
     container_name: pihole
     ports:
       - "53:53/tcp"
       - "53:53/udp"
     dns:
       - 127.0.0.1
       - 1.1.1.1
     environment:
       TZ: 'Asia/Dhaka'
       WEBPASSWORD: 'ChangeMeNow'
       PIHOLE_DNS: 1.1.1.1;9.9.9.9
       DNSSEC: 'false'
       VIRTUAL_HOST: pihole.tawfiqulbari.local
       WEBTHEME: default-dark
       PIHOLE_DOMAIN: lan
     volumes:
       - '~/pihole/pihole:/etc/pihole'
       - '~/pihole/dnsmasq.d:/etc/dnsmasq.d'
     restart: unless-stopped
     networks:
       - traefik
     labels:
       - traefik.enable=true
       - traefik.http.routers.pihole.rule=Host(`pihole.tawfiqulbari.local`)
       - traefik.http.routers.pihole.tls=true
       - traefik.http.routers.pihole.entrypoints=websecure
       - traefik.http.services.pihole.loadbalancer.server.port=80

networks:
  traefik:
    driver: bridge
    name: traefik
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
